version: "3"

services:
  backend:
    # DockerHub 이미지 주소
    image: juseungl/investi-mate
    container_name: backend
    expose:
      - 8080
    networks:
      - investimate

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_docker/nginx.conf:/etc/nginx/conf.d/default.conf # 왼쪽이 로컬 경로, 오른쪽이 도커 컨테이너 내부 경로
    # 서비스 종속관계 명시
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    networks:
      - investimate

networks:
  investimate:
