version: "3"

services:
  backend:
    # DockerHub 이미지 주소
    image: juseung/investi-mate:backend
    container_name: backend-container
    expose:
      - 8080
    networks:
      - investimate

  nginx:
    image: juseung/investi-mate:nginx
    container_name: nginx-container
    # 서비스 종속관계 명시
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    networks:
      - investimate

networks:
  investimate: